"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const node_path_1 = __importDefault(require("node:path"));
const Fs = __importStar(require("node:fs"));
const node_test_1 = require("node:test");
const node_assert_1 = __importDefault(require("node:assert"));
const live_runner_1 = require("../../live-runner");
const live_entity_1 = require("../../live-entity");
const __1 = require("../../..");
const utility_1 = require("../../utility");
(0, utility_1.loadEnvLocal)(__dirname + '/../../../.env.local');
(0, node_test_1.describe)('PushEntity', async () => {
    // Per-test live pacing. Delay is read from sdk-test-control.json's
    // `test.live.delayMs`; only sleeps when CODATPLATFORM_TEST_LIVE=TRUE.
    (0, node_test_1.afterEach)((0, utility_1.liveDelay)('CODATPLATFORM_TEST_LIVE'));
    (0, node_test_1.test)('instance', async () => {
        const testsdk = __1.CodatplatformSDK.test();
        const ent = testsdk.Push();
        (0, node_assert_1.default)(null != ent);
    });
    (0, node_test_1.test)('basic', async (t) => {
        const live = 'TRUE' === process.env.CODATPLATFORM_TEST_LIVE;
        for (const op of ['list', 'load']) {
            if (!live && (0, utility_1.maybeSkipControl)(t, 'entityOp', 'push.' + op, live))
                return;
        }
        const setup = basicSetup();
        if (setup.live) {
            return (0, live_entity_1.runLiveEntity)(setup, { "active": true, "alias": { "field": {} }, "fields": { "changes": { "a": true, "h": "Changes", "n": "changes", "r": false, "sh": "Contains a single entry that communicates which record has changed and the manner in which it changed.", "t": "`$ARRAY`", "key$": "changes", "index$": 0 }, "companyId": { "a": true, "fo": "uuid", "h": "Company Id", "n": "companyId", "r": true, "sh": "Unique identifier for your SMB in Codat.", "t": "`$STRING`", "key$": "companyId", "index$": 1 }, "completedOnUtc": { "a": true, "h": "Completed On Utc", "n": "completedOnUtc", "r": false, "sh": "The datetime when the push was completed, null if Pending.", "t": "`$STRING`", "key$": "completedOnUtc", "index$": 2 }, "dataConnectionKey": { "a": true, "fo": "uuid", "h": "Data Connection Key", "n": "dataConnectionKey", "r": true, "sh": "Unique identifier for a company's data connection.", "t": "`$STRING`", "key$": "dataConnectionKey", "index$": 3 }, "dataType": { "a": true, "h": "Data Type", "n": "dataType", "r": false, "sh": "The type of data being pushed, eg invoices, customers.", "t": "`$STRING`", "key$": "dataType", "index$": 4 }, "errorMessage": { "a": true, "h": "Error Message", "n": "errorMessage", "r": false, "sh": "A message about the error.", "t": "`$STRING`", "key$": "errorMessage", "index$": 5 }, "id": { "a": true, "h": "Id", "n": "id", "r": false, "t": "`$STRING`", "key$": "id", "index$": 6 }, "links": { "a": true, "h": "Links", "n": "links", "r": true, "t": "`$OBJECT`", "key$": "links", "index$": 7 }, "pageNumber": { "a": true, "h": "Page Number", "n": "pageNumber", "r": true, "sh": "Current page number.", "t": "`$INTEGER`", "key$": "pageNumber", "index$": 8 }, "pageSize": { "a": true, "h": "Page Size", "n": "pageSize", "r": true, "sh": "Number of items to return in results array.", "t": "`$INTEGER`", "key$": "pageSize", "index$": 9 }, "pushOperationKey": { "a": true, "fo": "uuid", "h": "Push Operation Key", "n": "pushOperationKey", "r": true, "sh": "A unique identifier generated by Codat to represent this single push operation.", "t": "`$STRING`", "key$": "pushOperationKey", "index$": 10 }, "requestedOnUtc": { "a": true, "h": "Requested On Utc", "n": "requestedOnUtc", "r": true, "sh": "The datetime when the push was requested.", "t": "`$STRING`", "key$": "requestedOnUtc", "index$": 11 }, "results": { "a": true, "h": "Results", "n": "results", "r": false, "t": "`$ARRAY`", "key$": "results", "index$": 12 }, "status": { "a": true, "h": "Status", "n": "status", "r": true, "sh": "The current status of the push operation.", "t": "`$STRING`", "key$": "status", "index$": 13 }, "statusCode": { "a": true, "h": "Status Code", "n": "statusCode", "r": true, "sh": "Push status code.", "t": "`$INTEGER`", "key$": "statusCode", "index$": 14 }, "timeoutInMinutes": { "a": true, "fo": "int32", "h": "Timeout In Minutes", "n": "timeoutInMinutes", "r": false, "sh": "Number of minutes the push operation must complete within before it times out.", "t": "`$INTEGER`", "key$": "timeoutInMinutes", "index$": 15 }, "timeoutInSeconds": { "a": true, "de": true, "fo": "int32", "h": "Timeout In Seconds", "n": "timeoutInSeconds", "r": false, "sh": "Number of seconds the push operation must complete within before it times out.", "t": "`$INTEGER`", "key$": "timeoutInSeconds", "index$": 16 }, "totalResults": { "a": true, "h": "Total Results", "n": "totalResults", "r": true, "sh": "Total number of items.", "t": "`$INTEGER`", "key$": "totalResults", "index$": 17 }, "validation": { "a": true, "h": "Validation", "n": "validation", "r": false, "sh": "A human-readable object describing validation decisions Codat has made when pushing data into the platform.", "t": "`$OBJECT`", "key$": "validation", "index$": 18 } }, "id": { "field": "id", "name": "id" }, "name": "push", "op": { "list": { "input": "data", "name": "list", "points": [{ "a": true, "co": { "id": "GET /companies/{companyId}/push", "source": "openapi3", "version": 2 }, "g": { "params": [{ "a": true, "ex": "8a210b68-6988-11ed-a1eb-0242ac120002", "k": "param", "n": "company_id", "or": "company_id", "r": true, "t": "`$STRING`", "index$": 0 }], "query": [{ "a": true, "ex": "-modifiedDate", "k": "query", "n": "order_by", "or": "order_by", "r": false, "t": "`$STRING`", "index$": 0 }, { "a": true, "ex": 1, "k": "query", "n": "page", "or": "page", "r": false, "t": "`$INTEGER`", "index$": 1 }, { "a": true, "ex": 100, "k": "query", "n": "page_size", "or": "page_size", "r": false, "t": "`$INTEGER`", "index$": 2 }, { "a": true, "ex": "id=e3334455-1aed-4e71-ab43-6bccf12092ee", "k": "query", "n": "query", "or": "query", "r": false, "t": "`$STRING`", "index$": 3 }] }, "k": "http", "m": "GET", "o": "/companies/{companyId}/push", "q": { "exist": ["company_id", "order_by", "page", "page_size", "query"] }, "r": { "param": { "companyId": "company_id" } }, "s": [{ "lit": "companies" }, { "var": "company_id" }, { "lit": "push" }], "t": { "req": "`reqdata`", "res": "`body`" }, "index$": 0 }], "key$": "list" }, "load": { "input": "data", "name": "load", "points": [{ "a": true, "co": { "id": "GET /companies/{companyId}/push/{pushOperationKey}", "source": "openapi3", "version": 2 }, "g": { "params": [{ "a": true, "ex": "8a210b68-6988-11ed-a1eb-0242ac120002", "k": "param", "n": "company_id", "or": "company_id", "r": true, "t": "`$STRING`", "index$": 0 }, { "a": true, "k": "param", "n": "id", "or": "push_operation_key", "r": true, "t": "`$STRING`", "index$": 1 }] }, "k": "http", "m": "GET", "o": "/companies/{companyId}/push/{pushOperationKey}", "q": { "exist": ["company_id", "id"] }, "r": { "param": { "companyId": "company_id", "pushOperationKey": "id" } }, "s": [{ "lit": "companies" }, { "var": "company_id" }, { "lit": "push" }, { "var": "id" }], "t": { "req": "`reqdata`", "res": "`body`" }, "index$": 0 }], "key$": "load" } }, "relations": { "ancestors": [["$.main.kit.entity.company"]] }, "key$": "push", "name__orig": "push", "Name": "Push", "name_": "push", "name-": "push", "NAME": "PUSH", "index$": 11 }, { "active": true, "entity": "push", "key$": "BasicPushFlow", "kind": "basic", "name": "BasicPushFlow", "param": {}, "step": [{ "a": true, "d": {}, "i": {}, "m": { "company_id": "company01" }, "o": "list", "s": [], "v": [{ "apply": "ItemExists", "def": { "ref": "push_ref01" } }], "index$": 0 }, { "a": true, "d": {}, "i": { "ref": "push_ref01", "srcdatavar": "push_ref01_data", "suffix": "_dt0" }, "m": { "company_id": "company01", "id": "push01" }, "o": "load", "s": [], "v": [{ "apply": "TextFieldMark", "def": { "mark": "Mark01-push_ref01" } }], "index$": 1 }] }, 'Push', { "GET /companies/{companyId}/push": { "protocol": "http", "parameters": [{ "name": "companyId", "in": "path", "required": true, "schema": { "type": "string", "format": "uuid", "example": "8a210b68-6988-11ed-a1eb-0242ac120002", "description": "Unique identifier for your SMB in Codat." }, "description": "Unique identifier for a company.", "x-ref": "#/components/parameters/companyId", "index$": 0 }, { "name": "page", "in": "query", "schema": { "type": "integer", "format": "int32", "minimum": 1, "example": 1, "default": 1 }, "description": "Page number. [Read more](https://docs.codat.io/using-the-api/paging).", "x-ref": "#/components/parameters/page", "index$": 1 }, { "name": "pageSize", "in": "query", "schema": { "type": "integer", "format": "int32", "default": 100, "example": 100, "minimum": 1, "maximum": 5000 }, "description": "Number of records to return in a page. [Read more](https://docs.codat.io/using-the-api/paging).", "x-ref": "#/components/parameters/pageSize", "index$": 2 }, { "name": "query", "in": "query", "required": false, "schema": { "type": "string" }, "example": "id=e3334455-1aed-4e71-ab43-6bccf12092ee", "description": "Codat query string. [Read more](https://docs.codat.io/using-the-api/querying).", "x-ref": "#/components/parameters/query", "index$": 3 }, { "name": "orderBy", "in": "query", "required": false, "schema": { "type": "string", "example": "-modifiedDate" }, "description": "Field to order results by. [Read more](https://docs.codat.io/using-the-api/ordering-results).", "x-ref": "#/components/parameters/orderBy", "index$": 4 }] }, "GET /companies/{companyId}/push/{pushOperationKey}": { "protocol": "http", "parameters": [{ "name": "companyId", "in": "path", "required": true, "schema": { "type": "string", "format": "uuid", "example": "8a210b68-6988-11ed-a1eb-0242ac120002", "description": "Unique identifier for your SMB in Codat." }, "description": "Unique identifier for a company.", "x-ref": "#/components/parameters/companyId", "index$": 0 }, { "schema": { "type": "string", "format": "uuid" }, "name": "pushOperationKey", "in": "path", "required": true, "description": "Push operation key.", "index$": 1 }] } });
        }
        const client = setup.client;
        const struct = setup.struct;
        const isempty = struct.isempty;
        const select = struct.select;
        let push_ref01_data = Object.values(setup.data.existing.push)[0];
        // LIST
        const push_ref01_ent = client.Push();
        const push_ref01_match = {};
        push_ref01_match['company_id'] = setup.idmap['company01'];
        const push_ref01_list = (await push_ref01_ent.list(push_ref01_match)).map((e) => e.data());
        // LOAD
        const push_ref01_match_dt0 = {};
        push_ref01_match_dt0.id = push_ref01_data.id;
        const push_ref01_data_dt0 = (await push_ref01_ent.load(push_ref01_match_dt0)).data();
        (0, node_assert_1.default)(push_ref01_data_dt0.id === push_ref01_data.id);
    });
});
function basicSetup(extra) {
    // TODO: fix test def options
    const options = {}; // null
    // TODO: needs test utility to resolve path
    const entityDataFile = node_path_1.default.resolve(__dirname, '../../../../.sdk/test/entity/push/PushTestData.json');
    // TODO: file ready util needed?
    const entityDataSource = Fs.readFileSync(entityDataFile).toString('utf8');
    // TODO: need a xlang JSON parse utility in voxgig/struct with better error msgs
    const entityData = JSON.parse(entityDataSource);
    options.entity = entityData.existing;
    let client = __1.CodatplatformSDK.test(options, extra);
    const struct = client.utility().struct;
    const merge = struct.merge;
    const transform = struct.transform;
    let idmap = transform(['push01', 'push02', 'push03', 'company01', 'company02', 'company03'], {
        '`$PACK`': ['', {
                '`$KEY`': '`$COPY`',
                '`$VAL`': ['`$FORMAT`', 'upper', '`$COPY`']
            }]
    });
    const env = (0, utility_1.envOverride)({
        'CODATPLATFORM_TEST_PUSH_ENTID': idmap,
        'CODATPLATFORM_TEST_LIVE': 'FALSE',
        'CODATPLATFORM_TEST_EXPLAIN': 'FALSE',
        'CODATPLATFORM_APIKEY': '',
    });
    idmap = env['CODATPLATFORM_TEST_PUSH_ENTID'];
    const live = 'TRUE' === env.CODATPLATFORM_TEST_LIVE;
    const transport = (0, live_runner_1.createLiveTransport)();
    if (live) {
        const rawIds = process.env['CODATPLATFORM_TEST_PUSH_ENTID'];
        idmap = rawIds && rawIds.trim() ? JSON.parse(rawIds) : {};
        if (!idmap || Array.isArray(idmap) || typeof idmap !== 'object') {
            throw new Error('Live ENTID must be a JSON object');
        }
        client = new __1.CodatplatformSDK(merge([
            // FIRST, so the generated fields below win: sdk-test-control.json's
            // test.client.options adds to the live client, it does not redirect it.
            (0, utility_1.liveClientOptions)(),
            {
                apikey: env.CODATPLATFORM_APIKEY,
            },
            // 'extra || {}', not a bare 'extra': struct.merge returns UNDEFINED when the
            // last entry is undefined, and basicSetup is normally called with no
            // argument at all - so a bare 'extra' silently discarded the apikey
            // and server values above and handed the SDK undefined. Harmless
            // while there was nothing in that object; not harmless now.
            extra || {},
            { system: { fetch: transport.fetch } }
        ]));
    }
    const setup = {
        idmap,
        env,
        options,
        client,
        struct,
        data: entityData,
        explain: 'TRUE' === env.CODATPLATFORM_TEST_EXPLAIN,
        live,
        transport,
        now: Date.now(),
    };
    return setup;
}
//# sourceMappingURL=PushEntity.test.js.map