<?php
declare(strict_types=1);

// Codatplatform SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

CodatplatformUtility::setRegistrar(function (CodatplatformUtility $u): void {
    $u->clean = [CodatplatformClean::class, 'call'];
    $u->done = [CodatplatformDone::class, 'call'];
    $u->make_error = [CodatplatformMakeError::class, 'call'];
    $u->feature_add = [CodatplatformFeatureAdd::class, 'call'];
    $u->feature_hook = [CodatplatformFeatureHook::class, 'call'];
    $u->feature_init = [CodatplatformFeatureInit::class, 'call'];
    $u->fetcher = [CodatplatformFetcher::class, 'call'];
    $u->make_fetch_def = [CodatplatformMakeFetchDef::class, 'call'];
    $u->make_context = [CodatplatformMakeContext::class, 'call'];
    $u->make_options = [CodatplatformMakeOptions::class, 'call'];
    $u->make_request = [CodatplatformMakeRequest::class, 'call'];
    $u->make_response = [CodatplatformMakeResponse::class, 'call'];
    $u->make_result = [CodatplatformMakeResult::class, 'call'];
    $u->make_point = [CodatplatformMakePoint::class, 'call'];
    $u->make_spec = [CodatplatformMakeSpec::class, 'call'];
    $u->make_url = [CodatplatformMakeUrl::class, 'call'];
    $u->param = [CodatplatformParam::class, 'call'];
    $u->prepare_auth = [CodatplatformPrepareAuth::class, 'call'];
    $u->prepare_body = [CodatplatformPrepareBody::class, 'call'];
    $u->prepare_headers = [CodatplatformPrepareHeaders::class, 'call'];
    $u->prepare_method = [CodatplatformPrepareMethod::class, 'call'];
    $u->prepare_params = [CodatplatformPrepareParams::class, 'call'];
    $u->prepare_path = [CodatplatformPreparePath::class, 'call'];
    $u->prepare_query = [CodatplatformPrepareQuery::class, 'call'];
    $u->graphql_body = [CodatplatformGraphql::class, 'body'];
    $u->graphql_errors = [CodatplatformGraphql::class, 'errors'];
    $u->result_basic = [CodatplatformResultBasic::class, 'call'];
    $u->result_body = [CodatplatformResultBody::class, 'call'];
    $u->result_headers = [CodatplatformResultHeaders::class, 'call'];
    $u->transform_request = [CodatplatformTransformRequest::class, 'call'];
    $u->transform_response = [CodatplatformTransformResponse::class, 'call'];
});
